// CART
export const DELETE_CART_ELEMENT = "APP/DELETE_CART_ELEMENT";
export const DELETE_CART_ELEMENTS = "APP/DELETE_CART_ELEMENTS";

export const DECREMENT_PIZZA_COUNTER = "APP/DECREMENT_PIZZA_COUNTER";
export const INCREMENT_PIZZA_COUNTER = "APP/INCREMENT_PIZZA_COUNTER";

export const ADD_TO_CART_ELEMENT = "APP/ADD_TO_CART_ELEMENT";

export const CHECK_LS_ITEMS = "APP/CHECK_LS_ITEMS";
// SHOP

export const IS_ADDED_TO_CARD = "APP/IS_ADDED_TO_CARD"
export const UN_ADDED_TO_CARD = "APP/UN_ADDED_TO_CARD"
export const UN_ADDED_ALL_TO_CARD = "APP/UN_ADDED_ALL_TO_CARD"

export const FILL_CONTENT = "APP/UPLOAD_CONTENT"

export const IS_BUIED_T = "APP/IS_BUIED_T";
export const IS_BUIED_F = "APP/IS_BUIED_F";

// APP

export const LOADING_ON = "APP/LOADING_ON";
export const LOADING_OFF = "APP/LOADING_OFF";
